SUBDIR=	arch base64 basename cat chown chmod chroot comm cp \
	cut date dd dirname du echo env expand expr factor false \
	fmt fold head hostid hostname id join link ln logname \
	ls mkdir mkfifo mknod mktemp mv nice nl nohup nproc \
	paste pathchk pr printenv printf pwd realpath rm \
	rmdir seq sleep split stat stty sync tail tee test \
	touch tr true tty uname unexpand uniq unlink users \
	wc who xinstall yes

.include <bsd.subdir.mk>
