SUBDIR=apply arch banner base64 basename cal calendar cmp diff dirname du env \
	expand false fmt fold getopt grep head hexdump id join locate logname \
	nice patch pathchk printenv printf realpath sed seq renice true tty \
	uname unexpand xargs yes

.include <bsd.subdir.mk>
