SUBDIR=apply arch banner base64 basename cal calendar cmp diff dirname du env \
	expand false fmt fold getopt grep head hexdump id join jot locate logname \
	nice patch pathchk printenv printf realpath sed seq stat renice true tty \
	uname unexpand unvis vis xargs yes

.include <bsd.subdir.mk>
