SUBDIR=apply banner base64 basename cal calendar cmp csplit comm diff \
	dirname du env expand false fmt fold getopt grep head hexdump id \
	join jot locate logname mkfifo mktemp nice nl patch pathchk printenv \
	printf realpath sed seq split stat renice tail tee tr true tty uname \
	unexpand uniq unvis vis wc whereis xargs yes

.include <bsd.subdir.mk>
